pipeline:
  identifier: Build_zuul_1731437590525
  name: Build zuul
  orgIdentifier: TPMLabs
  projectIdentifier: testal
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: test_al
        repoName: zuul
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencies
                  identifier: Install_dependencies
                  spec:
                    shell: Sh
                    command: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib gspread
              - step:
                  type: Action
                  name: Setup Gradle
                  identifier: Setup_Gradle
                  spec:
                    uses: gradle/gradle-build-action@v2
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    command: ./gradlew build -x test --continue --profile
              - step:
                  type: Test
                  name: Test
                  identifier: Test
                  spec:
                    shell: Sh
                    command: ./gradlew test --continue --profile
                    intelligenceMode: true
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: testal
                    repo: alsharma9/zuul
                    tags:
                      - <+pipeline.sequenceId>
                    caching: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
